services: {
    devcontainer: {
        image: "mcr.microsoft.com/devcontainers/base:ubuntu",
        volumes: [ "../..:/workspaces:cached" ],
        network_mode: "service:db",
        command: "sleep infinity",
    },
    db: {
        image: "postgres:14",
        restart: "unless-stopped",
        volumes: [ "postgres-data:/var/lib/postgresql/data" ],
        environment: { 
            "POSTGRES_PASSWORD": "",
            "POSTGRES_USER": "postgres",
            "POSTGRES_DB": "cxpay",
            "POSTGRES_HOST_AUTH_METHOD": "trust"
        },
    },
}

volumes: { postgres-data: }
